# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160924_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(upload_to='static/Commons/Images/user_face/'),
        ),
    ]
